### ISSUE TITLE
Large status bar icon in FF36

### ISSUE THREAD

**Issue by VladV** [klemens/ff-flashdisable#6]
Hello.

After some upgrades - I guess, FF 35->36 - the status bar icon for FlashDisable became twice as large as other icons, thus "pushing" the status bar to be too wide.
Here is a screenshot: https://dl.dropboxusercontent.com/u/644287/FlashDisable_StatusBar.jpg

I use Linux Qiana, FF 36 with Classic Theme Restorer installed.

Regards,
Vlad

**Comment by klemens** [comment]
I have had [similar problems](http://forums.mozillazine.org/viewtopic.php?p=13689905#p13689905) in the past.

The problem comes from that fact that I am using an vector based image for the button that has no fixed size. So the size should be set by the firefox theme or the extension that modifies it like in this case.
However it seems that nobody ever thinks about vector images, which is why even in the default firefox theme, placing my button in the default toolbar alters the toolbar itself (although not quite as bad, just about one pixel)

I will think about reverting to pixel images, which would fix the issue, but loose the flexibility and elegance of the vector image. (eg vector images automatically work for HDPI screens)

You (or I) could also contact Aris (which is the author of Classic Theme Restorer), I am sure he will fix this. ;-)

**Comment by Aris-t2** [comment]
Hi,

neither vector images nor add-ons, that provide additional toolbars, are the main reason for this glitch, but a bug in Firefox for Linux.

I reported this issue a while ago after a user mentioned a similar problem with another add-on on Linux.

Look here: https://bugzilla.mozilla.org/show_bug.cgi?id=1138050

It is possible to add additional code to shrink such icons for CTRs add-on bar for example, but what about all other toolbars, e.g. the default ones like bookmarks toolbar or menu toolbar? They are affected by this glitch even without any other toolbar add-ons installed.

I guess the more people confirm this Linux bug the sooner someone at Mozilla will fix it.

Here is a temporal fix to be used in Stylish add-on:

toolbar:not(#nav-bar):not(#TabsToolbar) toolbarbutton[id="action-button--jid0-bba9vaawx3lmwdu668audrpqvxujetpack-flash-disable-button"] .toolbarbutton-badge-container image {
  width: 16px !important;
  height: 16px !important;
  padding: 0 !important;
  margin: 0 !important;
}

**Comment by klemens** [comment]
Ok, seems I was a little bit fast on this one.
Thanks for the info! I left a vote at your bug.

**Comment by ganego** [comment]
Just upgraded to FF nightly x64 v40 on W7x64 and have a similar bug.
The icon now goes over half my screen. I disabled classic theme restorer but that didn't do anything.
I went back to nightly x64 v39 - without any changes to addons or so - and the icon works fine again.

**Comment by Aris-t2** [comment]
This Fx40 (Nightly) bug is present for a few days now. No add-on is responsible for this one.

You can fix it temporarily by using/modifying this code

toolbar toolbarbutton[id^="toggle-button-"] .toolbarbutton-badge-container .toolbarbutton-icon,
toolbar toolbarbutton[id^="action-button-"] .toolbarbutton-badge-container .toolbarbutton-icon {
  width: 18px !important;
}
#nav-bar toolbarbutton[id^="toggle-button-"] .toolbarbutton-badge-container .toolbarbutton-icon,
#nav-bar toolbarbutton[id^="action-button-"] .toolbarbutton-badge-container .toolbarbutton-icon {
  margin: -1px !important;
} 

Using CTRs small button mode requires additionally this code

#nav-bar toolbarbutton[id*="jetpack-flash-disable-button"] .toolbarbutton-badge-container .toolbarbutton-icon {
  padding: 3px !important;
}

**Comment by klemens** [comment]
It seems this second issue will be fixed in the next nightly (2015-04-14): https://bugzilla.mozilla.org/show_bug.cgi?id=1153243

**Comment by klemens** [comment]
I made a new version which includes a workaround (6951ab6c5d68236de5591a0736a91a0c8919f7d9) that should fix most of these problems in the future: I just "resized" the svgs to 16 by 16 pixels, which firefox seems to respect.
The reason for this workaround is the fact that the button was displayed with 18x18px in the current stable version (didn't notice this before because of my custom theme modifications), which caused the navigation toolbar's height to increase. However this seems to be fixed in the current nightly.
